
openapi: "3.0.2"
info:
  title: Veroo Organization Management BFF API
  version: "0.1"
  description:
    $ref: ./some.md
servers:
  - url: https://admin-bff.org.veroo.io/v1
  - url: https://party-service.org.veroo.io/admin-bff/v1
paths:
  /organizations:
    description: >
      This resource represents the collection of organizations interacting with the Veroo
      platform.
    get:
      tags:
        - Organizations
      summary: Get organizations
      operationId: getOrganizations
      description:
        $ref: ./some.md
      security:
        - OAuth2: ["read:organizations"]
  /organizations/search:
    description: >
      This resource represents sorted and filtered organizations interacting with the Veroo
      platform.
    post:
      tags:
        - Organizations
      summary: Get sorted and filtered organizations
      operationId: getOrganizationsSortedAndFiltered
      description: >
        [GET with body payload](https://opensource.zalando.com/restful-api-guidelines/#get-with-body) - no resources created:
        Returns filtered and sorted Organizations.
      security:
        - OAuth2: ["read:organizations"]
  /organizations/{id}:
    description: >
      This resource represents a single organization. Each organization is identified by
      an alphanumeric `id`.
    get:
      tags:
        - Organizations
      summary: Get organization by id
      operationId: getOrganization
      description: >
        Load organization details for a given `id`.
      security:
        - OAuth2: ["read:organizations"]
  /organizations/{id}/connections/search:
    description: >
      This resource represents sorted and filtered connections of the organization specified by the id.
    post:
      tags:
        - Organizations
      summary: Get sorted and filtered connections of organization
      operationId: getConnectionsOfOrganizationSortedAndFiltered
      description: >
        [GET with body payload](https://opensource.zalando.com/restful-api-guidelines/#get-with-body) - no resources created:
        Returns filtered and sorted Connections of an Organization.
      security:
        - OAuth2: ["read:organizations"]
  /organizations/{id}/business-interactions/search:
    description: >
      This resource represents sorted and filtered business interactions of the organization specified by the id.
    post:
      tags:
        - Organizations
      summary: Get sorted and filtered business interactions of organization
      operationId: getBusinessInteractionsOfOrganizationSortedAndFiltered
      description: >
        [GET with body payload](https://opensource.zalando.com/restful-api-guidelines/#get-with-body) - no resources created:
        Returns filtered and sorted Business Interactions of an Organization.
      security:
        - OAuth2: ["read:organizations"]
  /applications:
    description: >
      This resource client applications of an organization.
    get:
      tags:
        - Client Applications
      summary: Get client applications of organization
      operationId: getClientApplications
      description: Returns client applications of an organization from CAM.
      security:
        - OAuth2: ["read:applications"]
    post:
      tags:
        - Client Applications
      summary: Create client application for organization
      operationId: createClientApplication
      description: Creates client application for an organization from CAM.
      security:
        - OAuth2: ["write:applications"]
  /applications/{appId}:
    description: >
      This resource client applications of an organization.
    delete:
      tags:
        - Client Applications
      summary: Delete client application
      operationId: deleteClientApplication
      description: Delete client application from CAM.
      security:
        - OAuth2: ["write:applications"]
  /applications/{appId}/rotate-secret:
    description: >
      This resource client applications of an organization.
    post:
      tags:
        - Client Applications
      summary: Rotate client secret for client application
      operationId: rotateClientApplicationSecret
      description: Rotate client secret of client application from CAM.
      security:
        - OAuth2: ["write:applications"]
  /applications/{appId}/block:
    description: >
      This resource client applications of an organization.
    post:
      tags:
        - Client Applications
      summary: Block client application
      operationId: blockClientApplication
      description: Block client application from CAM.
      security:
        - OAuth2: ["write:applications"]
  /applications/{appId}/activate:
    description: >
      This resource client applications of an organization.
    post:
      tags:
        - Client Applications
      summary: Activate client application
      operationId: activateClientApplication
      description: Activate client application from CAM.
      security:
        - OAuth2: ["write:applications"]
  /users:
    description: >
      This resource represents the collection of users interacting with the Veroo
      platform.
    get:
      tags:
        - Users
      summary: Get users
      operationId: getUsers
      description: >
        Get all users
      security:
        - OAuth2: ["read:users"]
  /users/search:
    description: >
      This resource represents sorted and filtered users interacting with the Veroo
      platform.
    post:
      tags:
        - Users
      summary: Get sorted and filtered users
      operationId: getUsersSortedAndFiltered
      description: >
        [GET with body payload](https://opensource.zalando.com/restful-api-guidelines/#get-with-body) - no resources created:
        Returns filtered and sorted Users.
      security:
        - OAuth2: ["read:users"]
  /users/{id}:
    description: >
      This resource represents a single user. Each user is identified by
      an alphanumeric `id`.
    get:
      tags:
        - Users
      summary: Get user by id
      operationId: getUser
      description: >
        Load user details for a given `id`.
      security:
        - OAuth2: ["read:users"]
  /customers:
    description: >
      This resource represents the collection of customers interacting with the Veroo
      platform.
    post:
      tags:
        - Customers
      summary: Create customer
      operationId: createCustomer
      description: >
        Creates a customer for a given party id.
      security:
        - OAuth2: ["write:organizations"]
  /customers/{id}/users:
    description: >
      This resource represents all users of a customers.
    get:
      tags:
        - Customers
      summary: Get user by customer
      operationId: getUsersByCustomer
      description: >
        Load users for a customer.
      security:
        - OAuth2: ["read:organizations", "read:users"]
  /customers/{id}/user-invitations:
    description: >
      Create an invitation for a new user to join this customer.
    post:
      tags:
        - Customers
      summary: Create user invitation for customer
      operationId: createUserInvitationForCustomer
      description: >
        Creates a user invitation for the given customer.
      security:
        - OAuth2: ["write:organizations", "write:users"]
    get:
      tags:
        - Customers
      summary: Get user invitations for a customer
      operationId: getUserInvitationsForCustomer
      description: >
        This resource represents the user invitations of a given customer.
      security:
        - OAuth2: ["read:organizations"]
  /customers/{id}/user-invitations/{invitationId}:
    get:
      tags:
        - Customers
      summary: Get user invitation by id for a customer
      operationId: getUserInvitationForCustomer
      description: >
        This resource represents the user invitation of a given customer.
      security:
        - OAuth2: ["read:organizations"]
    put:
      deprecated: true
      tags:
        - Customers
      summary: Update and resend user invitation for customer
      operationId: updateUserInvitationForCustomer
      description: >
        Updates and resends a user invitation for the given customer. For now, only the validityPeriod can be changed. Updating the other fields is not allowed yet and will result in an error.
      security:
        - OAuth2: ["write:organizations", "write:users"]
  /customers/{id}/user-invitations/{invitationId}/resend:
    description: This resource represents Customer User Invitations.
    post:
      tags:
        - Customers
      summary: Resend user invitation for customer
      operationId: resendUserInvitation
      description: >
        Resends a user invitation for the given customer.
      security:
        - OAuth2: ["write:organizations", "write:users"]
  /customers/{id}/user-invitations/{invitationId}/withdraw:
    description: This resource represents Customer User Invitations.
    post:
      tags:
        - Customers
      summary: Withdraw user invitation for customer
      operationId: withdrawUserInvitation
      description: >
        Withdraws a user invitation for the given customer.
      security:
        - OAuth2: ["write:organizations", "write:users"]
  /customers/{id}/additional-user-identification:
    get:
      tags:
        - Customers
      summary: Identify additional users to add to a customer
      operationId: identifyAdditionalUsersForCustomer
      description: |
        Identify possible users to add to a customer by
        - searching for existing users based on an email or name sub-string matching and evaluating their state and also
        - evaluating whether the searched user can be added or invited to the customer
        - if a user matches the searchterm exactly, he will be on the start of the list
      security:
        - OAuth2: [ "read:organizations", "read:users" ]
  /carriers:
    description: >
      This resource represents the collection of carriers interacting with the Veroo
      platform.
    post:
      tags:
        - Carriers
      summary: Create carrier
      operationId: createCarrier
      description: >
        Creates a carrier for a given party id.
      security:
        - OAuth2: ["write:organizations"]
  /shippers:
    description: >
      This resource represents the collection of shippers interacting with the Veroo
      platform.
    post:
      tags:
        - Shippers
      summary: Create shipper
      operationId: createShipper
      description: >
        Creates a shipper for a given party id.
      security:
        - OAuth2: ["write:organizations"]
  /customers/{id}/users/{userId}:
    put:
      tags:
        - Customers
      summary: Associate customer and user
      operationId: associateCustomerAndUser
      description: >
        Associates customer and user with roles
      security:
        - OAuth2: ["write:organizations"]
    delete:
      tags:
        - Customers
      summary: Delete customer-user association
      operationId: deleteCustomerUserAssociation
      description: >
        Deletes Association between the customer and user
      security:
        - OAuth2: ["write:organizations"]
  /customer-setup-vouchers:
    post:
      summary: Create a customer-setup-voucher
      description: Create a customer-setup-voucher
      operationId: postCustomerSetupVoucher
      tags:
        - Customer Setup Vouchers
  /customer-setup-vouchers/{id}/logs:
    description: This resource represents Customer Setup Voucher Logs.
    get:
      tags:
        - Customer Setup Vouchers
      summary: Get Customer Setup Voucher Logs
      operationId: getCustomerSetupVoucherLogs
      description: Get Customer Setup Voucher Logs by Customer Setup Voucher id
      security:
        - OAuth2: [ "read:customer-setup-vouchers" ]
  /customer-setup-vouchers/{id}:
    get:
      tags:
        - Customer Setup Vouchers
      summary: Get Customer Setup Voucher by id
      operationId: getCustomerSetupVoucherById
      description: Get Customer Setup Voucher by id
      security:
        - OAuth2: [ "read:customer-setup-vouchers" ]
  /customer-setup-vouchers/{id}/withdraw:
    post:
      tags:
        - Customer Setup Vouchers
      summary: Withdraw Customer Setup Voucher
      operationId: withdrawCustomerSetupVouchers
      description: Withdraw Customer Setup Voucher
      security:
        - OAuth2: [ "write:customer-setup-vouchers" ]
  /customer-setup-vouchers/{id}/reject:
    post:
      tags:
        - Customer Setup Vouchers
      summary: Reject Customer Setup Voucher
      operationId: rejectCustomerSetupVouchers
      description: Reject Customer Setup Voucher
      security:
        - OAuth2: [ "write:customer-setup-vouchers" ]
  /customer-setup-vouchers/{id}/extend:
    post:
      tags:
        - Customer Setup Vouchers
      summary: Extend Customer Setup Voucher
      operationId: extendCustomerSetupVouchers
      description: Extend the expiration date of a Customer Setup Voucher
      security:
        - OAuth2: [ "write:customer-setup-vouchers" ]
  /customer-setup-vouchers/{id}/resend:
    post:
      tags:
        - Customer Setup Vouchers
      summary: Resend Customer Setup Voucher
      operationId: resendCustomerSetupVouchers
      description: Resend Customer Setup Voucher (only possible for Customer Invitations)
      security:
        - OAuth2: [ "write:customer-setup-vouchers" ]
  /customer-setup-vouchers/{id}/redeem:
    post:
      tags:
        - Customer Setup Vouchers
      summary: Redeem Customer Setup Voucher
      operationId: redeemCustomerSetupVouchers
      description: Manually redeem Customer Setup Voucher
      security:
        - OAuth2: [ "write:customer-setup-vouchers" ]
  /customer-setup-vouchers/{id}/reopen:
    post:
      tags:
        - Customer Setup Vouchers
      summary: Reopen Customer Setup Voucher
      operationId: reopenCustomerSetupVouchers
      description: Reopen Customer Setup Voucher
      security:
        - OAuth2: [ "write:customer-setup-vouchers" ]
  /customer-setup-vouchers/search:
    description: This resource represents sorted and filtered Customer Setup Vouchers.
    post:
      tags:
        - Customer Setup Vouchers
      summary: Get sorted and filtered Customer Setup Vouchers
      operationId: getCustomerSetupVouchersSortedFiltered
      description: >
        [GET with body payload](https://opensource.zalando.com/restful-api-guidelines/#get-with-body) - no resources created:
        Returns filtered and sorted Customer Setup Vouchers.
      security:
        - OAuth2: [ "read:customer-setup-vouchers" ]
  /customer-setup-vouchers/{id}/identification-history:
    description:
      Identification history
    get:
      tags:
        - Customer Setup Vouchers
      summary: Identification history of a voucher
      description: >
        Get identification history of a voucher sorted by createdAt descending
  /customer-setup-vouchers/{id}/validate-vat-id:
    description:
      Manually validate the VAT-ID of a voucher
    post:
      tags:
        - Customer Setup Vouchers
      summary: Manually validate VAT-ID
      description: >
        Manually validate the VAT-ID of a voucher
  /search:
    description: >
      This resource is used to search for organizations, users and customer setup vouchers in the Veroo Platform.
    get:
      tags:
        - Search
      summary: Global Search
      operationId: search
      description: >
        Search Organizations, Users and Customer Setup Vouchers
      security:
        - OAuth2:
            ["read:organizations", "read:users", "read:customer-setup-vouchers"]
  /customer-setup-inquiries:
    description: This resource represents a customer-setup-inquiry.
    get:
      tags:
        - Customer Setup Inquiries
      operationId: getCustomerSetupInquiry
      summary: Get customer setup inquiry by voucher id
      description: Get a customer setup inquiry for a customer setup voucher
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login-stage.veroo.io/authorize
          tokenUrl: https://login-stage.veroo.io/oauth/token
          scopes:
            read:organizations: Grants access to read organizations
            write:organizations: Grants access to write and edit organizations
            read:users: Grants access to read users
            write:users: Grants access to write and edit users
            read:customer-setup-vouchers: Grants access to read customer setup vouchers
            write:customer-setup-vouchers: Grants access to write and edit customer setup vouchers
            read:applications: Grants access to read client applications
            write:applications: Grants access to write and edit client applications
